config/routes.rb
Rails.application.routes.draw do
  resources :bugs

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/bug.rb
class Bug < ActiveRecord::Base
  belongs_to :user

  has_many :bugs_assignees
  has_many :assignees, through: :bugs_assignees, source: :user


  LABELS = ['new', 'assigned', 'resolved', 're-open', 'verified', 'closed']

  validates :title, :status, :user_id, presence: true

  validates :status, inclusion: {in: LABELS,
                         message: "{{value}} must be in #{LABELS.join ','}"}


end

app/models/bugs_assignee.rb
class BugsAssignee < ActiveRecord::Base
  belongs_to :user
  belongs_to :bug


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bugs_assignees
  has_many :bugs, through: :bugs_assignees

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy]

  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :description, :status, :user_id, assignee_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_form.html.haml
= form_for @bug do |f|
  - if @bug.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bug.errors.count, "error")} prohibited this bug from being saved:"
      %ul
        - @bug.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :status
    = f.select :status, Bug::LABELS
  .field
    = f.label 'Owner'
    = f.select :user_id, User.pluck(:name, :id)
  .field
    = f.label 'Assignee'
    = f.select :assignee_ids, User.pluck(:name, :id), {}, :multiple => true


  .actions
    = f.submit 'Save'

app/views/bugs/edit.html.haml
%h1 Editing bug

= render 'form'

= link_to 'Show', @bug
\|
= link_to 'Back', bugs_path

app/views/bugs/index.html.haml
%h1 Listing bugs

%table
  %thead
    %tr
      %th Title
      %th Description
      %th Status
      %th Owner
      %th
      %th
      %th

  %tbody
    - @bugs.each do |bug|
      %tr
        %td= bug.title
        %td= bug.description
        %td= bug.status
        %td= bug.user.name
        %td= link_to 'Show', bug
        %td= link_to 'Edit', edit_bug_path(bug)
        %td= link_to 'Destroy', bug, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bug', new_bug_path

app/views/bugs/new.html.haml
%h1 New bug

= render 'form'

= link_to 'Back', bugs_path

app/views/bugs/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @bug.title
%p
  %b Description:
  = @bug.description
%p
  %b Status:
  = @bug.status
%p
  %b Owner:
  = @bug.user.name
%p
  %b Assignees:
  - @bug.assignees.each do |assignee|
    = "#{assignee.name},"


= link_to 'Edit', edit_bug_path(@bug)
\|
= link_to 'Back', bugs_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Profile', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Bugzilla ', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
/ add navigation links to this file
= render 'layouts/nav_links_for_auth'

app/views/layouts/_sidebar.html.haml
/ Sidebar
#sidebar-wrapper
  %ul.sidebar-nav
    %li.sidebar-brand
      %a{:href => "#"}
        Home
    - if user_signed_in?
      %li
        =link_to 'Bugs', bugs_path
      %li
        =link_to 'User', users_path
/ /#sidebar-wrapper

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Bugzilla'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Bugzilla'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      #wrapper
        = render 'layouts/sidebar'
        = yield

/ /#wrapper
/ Menu Toggle Script
:javascript
  $("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
  });

app/views/users/_user.html.haml
%td= link_to user.name, user
%td= link_to user.email, user

app/views/users/index.html.haml
.container
  .row
    %h3 Users
    .column
      %table.table
        %tbody
          - @users.each do |user|
            %tr
              = render user

app/views/users/show.html.haml
%h3 User
%p
  Name: #{@user.name if @user.name}
%p
  Email: #{@user.email if @user.email}

app/views/visitors/index.html.haml
/ Page Content
#page-content-wrapper
    .container-fluid
        .row
            .col-lg-12
                %h1 Simple Bug Tracking System
                %p With the following features:
                %ul
                    %li
                        Bugs start out as New.
                    %li
                        They are then Assigned or Resolved.
                    %li
                        Assigned bugs are then either Resolved or the ownership is changed.
                    %li
                        Resolved bugs can be Re-opened, Verified, or Closed.
                %a#menu-toggle.btn.btn-default{:href => "#menu-toggle"} Toggle Menu